# Tensorflow Basics 

In [14]:
import tensorflow as tf 

In [15]:
tf.__version__

'2.0.0'

In [16]:
hello = tf.constant("HELLO")
world = tf.constant("WORLD")

In [17]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [18]:
tf.print(hello)

HELLO


In [19]:
tf.print(world)

WORLD


# Add two values 

In [20]:
a=tf.constant(10)
b=tf.constant(20)
tf.print("value : {}".format(a+b))

value : 30


# Create constant 

In [21]:
const=tf.constant(10)

# Create matrix 

Create matrix 4*4 and fills witht the 10

In [22]:
fill_mat=tf.fill((4,4),10)

In [23]:
fill_mat

<tf.Tensor: id=38, shape=(4, 4), dtype=int32, numpy=
array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)>

Create 4*4 matirix and fill it with 0 

In [26]:
my_zeros=tf.zeros((4,4))
my_zeros

<tf.Tensor: id=44, shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Create 4*4 matrix with all 1 

In [27]:
my_ones =tf.ones((4,4))
my_ones

<tf.Tensor: id=47, shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

# Random normal distribution 

In [36]:
my_randn=tf.random.normal((8,6), mean=40, stddev=3.0)
my_randn

<tf.Tensor: id=89, shape=(8, 6), dtype=float32, numpy=
array([[40.027412, 40.83337 , 38.094547, 47.781693, 40.131676, 41.4349  ],
       [42.92204 , 44.709206, 37.102238, 38.632652, 37.88633 , 38.61011 ],
       [37.89195 , 34.493584, 38.11578 , 39.568687, 48.170227, 42.38642 ],
       [41.45662 , 37.495605, 35.909325, 39.666855, 38.47671 , 42.837315],
       [43.25914 , 38.995735, 42.439774, 45.184334, 36.46701 , 40.080997],
       [39.251606, 43.63725 , 39.65807 , 38.532143, 39.833183, 40.73056 ],
       [43.09242 , 45.05087 , 38.87869 , 41.840034, 44.959347, 38.472004],
       [42.78889 , 39.262985, 44.69831 , 41.82014 , 43.257607, 37.932262]],
      dtype=float32)>

# Uniform distribution

In [38]:
my_rand2=tf.random.uniform((4,4), minval=0, maxval=10)
my_rand2

<tf.Tensor: id=103, shape=(4, 4), dtype=float32, numpy=
array([[4.9655294, 4.045762 , 8.12119  , 8.370352 ],
       [4.508377 , 7.9196715, 8.340763 , 4.62294  ],
       [8.433523 , 4.395733 , 1.8276644, 2.6804066],
       [9.856926 , 6.977042 , 3.6766481, 8.931072 ]], dtype=float32)>

# Matrix multiplication 

In [40]:
a1=tf.constant([[1,2],
                [3,4]])

In [42]:
a1.get_shape()

TensorShape([2, 2])

In [43]:
a2=tf.constant([[5,6], 
               [7,8]])

In [46]:
result=tf.matmul(a1,a2)
tf.print(result)

[[19 22]
 [43 50]]
