# Tensorflow Basics 

In [14]:
import tensorflow as tf 

In [15]:
tf.__version__

'2.0.0'

In [16]:
hello = tf.constant("HELLO")
world = tf.constant("WORLD")

In [17]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [18]:
tf.print(hello)

HELLO


In [19]:
tf.print(world)

WORLD


# Add two values 

In [20]:
a=tf.constant(10)
b=tf.constant(20)
tf.print("value : {}".format(a+b))

value : 30


# Create constant 

In [21]:
const=tf.constant(10)

# Create matrix 

Create matrix 4*4 and fills witht the 10

In [22]:
fill_mat=tf.fill((4,4),10)

In [23]:
fill_mat

<tf.Tensor: id=38, shape=(4, 4), dtype=int32, numpy=
array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)>

Create 4*4 matirix and fill it with 0 

In [26]:
my_zeros=tf.zeros((4,4))
my_zeros

<tf.Tensor: id=44, shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Create 4*4 matrix with all 1 

In [27]:
my_ones =tf.ones((4,4))
my_ones

<tf.Tensor: id=47, shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

# Random normal distribution 

In [47]:
my_randn=tf.random.normal((8,6), mean=40, stddev=3.0)
tf.print(my_randn)

[[40.3418274 43.0806465 38.6448669 42.7617302 37.8302689 40.0101929]
 [35.506134 42.7404556 38.9363 46.0315208 41.0250473 42.1186485]
 [41.7019119 41.812851 38.0693169 40.3254585 45.3750343 38.046627]
 ...
 [39.7561111 34.6025543 42.9927559 41.6779976 42.984272 42.8481]
 [38.4859428 40.1022415 35.0236282 36.7194214 36.0107651 32.8739357]
 [40.4773674 42.7060623 35.6999283 38.7804871 41.0557289 41.3307571]]


# Uniform distribution

In [51]:
my_rand2=tf.random.uniform((9,9), minval=0, maxval=100)
tf.print(my_rand2)

[[86.6326828 62.565567 10.4278326 ... 2.18994617 19.1872597 42.6892624]
 [47.182106 50.158596 68.7467422 ... 47.6826057 57.175518 38.3387794]
 [2.90710926 10.1862907 94.5250168 ... 70.4874268 67.2672043 1.90476179]
 ...
 [79.7474289 12.1656179 27.0978928 ... 55.4550896 99.4526596 13.7830496]
 [91.4599533 22.9728222 39.5845184 ... 24.3697052 55.6638374 72.8603745]
 [59.2011795 18.7090149 20.1454391 ... 32.6651077 91.7043457 40.477562]]


# Matrix multiplication 

In [40]:
a1=tf.constant([[1,2],
                [3,4]])

In [42]:
a1.get_shape()

TensorShape([2, 2])

In [43]:
a2=tf.constant([[5,6], 
               [7,8]])

In [46]:
result=tf.matmul(a1,a2)
tf.print(result)

[[19 22]
 [43 50]]
