# Tensorflow Basics 

In [14]:
import tensorflow as tf 

In [15]:
tf.__version__

'2.0.0'

In [16]:
hello = tf.constant("HELLO")
world = tf.constant("WORLD")

In [17]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [18]:
tf.print(hello)

HELLO


In [19]:
tf.print(world)

WORLD


# Add two values 

In [20]:
a=tf.constant(10)
b=tf.constant(20)
tf.print("value : {}".format(a+b))

value : 30


# Create constant 

In [21]:
const=tf.constant(10)

# Create matrix 

Create matrix 4*4 and fills witht the 10

In [22]:
fill_mat=tf.fill((4,4),10)

In [23]:
fill_mat

<tf.Tensor: id=38, shape=(4, 4), dtype=int32, numpy=
array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)>

Create 4*4 matirix and fill it with 0 

In [26]:
my_zeros=tf.zeros((4,4))
my_zeros

<tf.Tensor: id=44, shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Create 4*4 matrix with all 1 

In [27]:
my_ones =tf.ones((4,4))
my_ones

<tf.Tensor: id=47, shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>