# Tensorflow basics 

In [1]:
import tensorflow as tf 

In [2]:
# check the version 
tf.__version__

'2.0.0'

In [3]:
# create 2 constant 
hello = tf.constant("HELLO")
world = tf.constant("WORLD")


2023-01-14 06:11:15.727824: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-14 06:11:15.731246: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.


In [5]:
# print two constant
tf.print(hello)
tf.print(world)

HELLO
WORLD


In [9]:
# add two numbers 
num1=tf.constant(10)
num2=tf.constant(40)
print("Addd: {}".format((num1+num2)))

Addd: 50


In [10]:
# create a matrix which fills with spesific number 
mat=tf.fill((4,4), 90)
tf.print(mat)

[[90 90 90 90]
 [90 90 90 90]
 [90 90 90 90]
 [90 90 90 90]]


In [14]:
# create a matrix which fills with 0 
mat0=tf.zeros((5,6), 10)
tf.print(mat0)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [17]:
# create a matirx which fills with all 1s
mat1=tf.ones((5,9))
tf.print(mat1)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
