# Tensorflow basics 

In [1]:
import tensorflow as tf 

In [2]:
# check the version 
tf.__version__

'2.0.0'

In [3]:
# create 2 constant 
hello = tf.constant("HELLO")
world = tf.constant("WORLD")


2023-01-14 06:11:15.727824: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-14 06:11:15.731246: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.


In [5]:
# print two constant
tf.print(hello)
tf.print(world)

HELLO
WORLD


In [9]:
# add two numbers 
num1=tf.constant(10)
num2=tf.constant(40)
print("Addd: {}".format((num1+num2)))

Addd: 50


In [10]:
# create a matrix which fills with spesific number 
mat=tf.fill((4,4), 90)
tf.print(mat)

[[90 90 90 90]
 [90 90 90 90]
 [90 90 90 90]
 [90 90 90 90]]


In [14]:
# create a matrix which fills with 0 
mat0=tf.zeros((5,6), 10)
tf.print(mat0)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [17]:
# create a matirx which fills with all 1s
mat1=tf.ones((5,9))
tf.print(mat1)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [19]:
# create a random unifrom matrix 
uni_mat=tf.random.uniform((9,9), minval=45, maxval=48)
tf.print(uni_mat)

[[45.6064758 47.2198753 46.6129761 ... 46.6603928 45.7262192 47.6430969]
 [46.0288887 45.2957153 47.5246162 ... 45.2862396 45.5949631 46.5833054]
 [46.1061783 46.0987396 46.1260681 ... 45.5570641 46.4175529 47.0636177]
 ...
 [46.9702034 45.7799034 45.6255798 ... 46.1880722 45.5583649 47.721611]
 [47.7295876 47.7302742 46.1754646 ... 47.8102913 45.0679779 47.668644]
 [45.8631401 45.2380791 45.8324699 ... 45.9280357 47.2680931 46.1967316]]


In [20]:
# Create random normal value matirx for given mean ans std 
nor_mat=tf.random.normal((10,10), mean=43, stddev=20)
tf.print(nor_mat)

[[78.2720642 67.0361633 50.0633774 ... 70.9680481 55.0310822 40.6136055]
 [43.0212631 52.2171249 48.889492 ... 64.9798126 54.1907806 61.3844299]
 [68.2216797 66.9434052 38.0519638 ... 42.8099709 7.18098068 85.5465393]
 ...
 [14.8097343 42.2226715 27.4330025 ... 19.6380405 45.5739441 57.1043091]
 [7.59243393 15.1258469 -2.41633224 ... 64.5407562 46.2130432 5.04676437]
 [48.7443581 85.5659 31.5392151 ... 45.3710976 3.75220871 53.302536]]


In [24]:
# matirix multlipication 
a1 = tf.constant([[2,3,3],
                 [4,5,9]])

a2 = tf.constant([[8,9],
                 [10,3],
                 [4,0]])
tf.print("Mat mul: {}".format(tf.matmul(a1,a2)))

Mat mul: [[ 58  27]
 [118  51]]


In [26]:
# craret 2 random uniform matrixs and multiply it 
ran_mat_1 = tf.random.uniform((5,6), minval=14, maxval=28)
ran_mat_2 = tf.random.uniform((6,5), minval=40, maxval=53)
tf.print("Mulplication")
tf.print(tf.matmul(ran_mat_1, ran_mat_2))

Mulplication
[[5733.14502 5670.97217 5688.72461 5940.31299 5684.19092]
 [5548.80078 5482.58643 5593.13428 5787.60547 5481.64404]
 [5961.56104 5813.0791 5915.29102 6154.27344 5804.45508]
 [6435.73 6330.6377 6328.26758 6574.87646 6348.17383]
 [5504.36719 5492.02881 5518.53564 5702.56445 5525.85352]]


# Tensorflow Graphs 

In [29]:
# get the default graph 
d_graph = tf.compat.v1.get_default_graph()
d_graph

In [31]:
#  create addition graph in TF
graph = tf.Graph()
graph

In [34]:
# set additional graph to the default graph 
with graph.as_default():
    print(graph is tf.compat.v1.get_default_graph())

True


# Variables and Placeholders 

In [36]:
# create TF variable. 
my_rand_matrix = tf.random.uniform((4,4), minval=12, maxval=34)
my_variable = tf.Variable(initial_value= my_rand_matrix)
tf.print(my_variable)

[[13.1927319 22.1690445 17.7869949 15.1582422]
 [33.6531067 31.6739388 12.7179279 25.4588909]
 [31.2507572 32.1613312 26.4029179 15.2637291]
 [30.7896919 19.6207542 33.9984131 21.0456123]]


In [38]:
#  create placeholder 
tf.compat.v1.disable_eager_execution()
placeholder = tf.compat.v1.placeholder(dtype=tf.float32, shape=(5,5))