# Tensorflow basics 

In [1]:
import tensorflow as tf 

In [2]:
# check the version 
tf.__version__

'2.0.0'

In [3]:
# create 2 constant 
hello = tf.constant("HELLO")
world = tf.constant("WORLD")


2023-01-14 06:11:15.727824: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-14 06:11:15.731246: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.


In [5]:
# print two constant
tf.print(hello)
tf.print(world)

HELLO
WORLD


In [9]:
# add two numbers 
num1=tf.constant(10)
num2=tf.constant(40)
print("Addd: {}".format((num1+num2)))

Addd: 50


In [10]:
# create a matrix which fills with spesific number 
mat=tf.fill((4,4), 90)
tf.print(mat)

[[90 90 90 90]
 [90 90 90 90]
 [90 90 90 90]
 [90 90 90 90]]


In [14]:
# create a matrix which fills with 0 
mat0=tf.zeros((5,6), 10)
tf.print(mat0)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [17]:
# create a matirx which fills with all 1s
mat1=tf.ones((5,9))
tf.print(mat1)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [19]:
# create a random unifrom matrix 
uni_mat=tf.random.uniform((9,9), minval=45, maxval=48)
tf.print(uni_mat)

[[45.6064758 47.2198753 46.6129761 ... 46.6603928 45.7262192 47.6430969]
 [46.0288887 45.2957153 47.5246162 ... 45.2862396 45.5949631 46.5833054]
 [46.1061783 46.0987396 46.1260681 ... 45.5570641 46.4175529 47.0636177]
 ...
 [46.9702034 45.7799034 45.6255798 ... 46.1880722 45.5583649 47.721611]
 [47.7295876 47.7302742 46.1754646 ... 47.8102913 45.0679779 47.668644]
 [45.8631401 45.2380791 45.8324699 ... 45.9280357 47.2680931 46.1967316]]


In [ ]:
# Create random normal value matirx for given mean ans std 
