# Variables

In [2]:
import tensorflow as tf

In [3]:
my_tensor=tf.random.uniform((4,4), 0,1)
tf.print(my_tensor)

[[0.443229675 0.868291736 0.806306481 0.936555862]
 [0.77079165 0.993771195 0.156830668 0.604859114]
 [0.314885497 0.351425767 0.197366595 0.43150878]
 [0.821564794 0.800428748 0.954038501 0.627435565]]


2023-01-14 07:06:59.307249: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-14 07:06:59.307765: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.


In [4]:
my_variable =tf.Variable(initial_value=my_tensor)

In [5]:
tf.print(my_variable)

[[0.443229675 0.868291736 0.806306481 0.936555862]
 [0.77079165 0.993771195 0.156830668 0.604859114]
 [0.314885497 0.351425767 0.197366595 0.43150878]
 [0.821564794 0.800428748 0.954038501 0.627435565]]


# Placeholders

In [6]:
# placeholders are not executable immediately so we need to disable eager exicution in TF 2 not in 1
tf.compat.v1.disable_eager_execution()
 
# # Create Placeholder
placeholder = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))