# Variables

In [22]:
import tensorflow as tf

In [23]:
my_tensor=tf.random.uniform((4,4), 0,1)
tf.print(my_tensor)

[[0.935404778 0.312024117 0.703841925 0.755627513]
 [0.809807062 0.6685009 0.404628754 0.164469361]
 [0.104091525 0.991054177 0.852307439 0.689428329]
 [0.664138556 0.269124269 0.513974428 0.182166815]]


In [24]:
my_variable =tf.Variable(initial_value=my_tensor)

In [25]:
tf.print(my_variable)

[[0.935404778 0.312024117 0.703841925 0.755627513]
 [0.809807062 0.6685009 0.404628754 0.164469361]
 [0.104091525 0.991054177 0.852307439 0.689428329]
 [0.664138556 0.269124269 0.513974428 0.182166815]]


# Placeholders

In [29]:
# placeholders are not executable immediately so we need to disable eager exicution in TF 2 not in 1
tf.compat.v1.disable_eager_execution()
 
# # Create Placeholder
a = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))

RuntimeError: tf.placeholder() is not compatible with eager execution.

In [30]:
a = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))

RuntimeError: tf.placeholder() is not compatible with eager execution.