# SciKIt Learn 

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

Create random multi-dimentional arrray

In [2]:
data=np.random.randint(0,100,(3,5))
data


array([[ 5, 73, 72, 34, 12],
       [22, 79, 83, 82, 84],
       [56, 15, 37, 98, 74]])

Normalize the data 

In [3]:
scalar=MinMaxScaler()
scalar.fit(data)

MinMaxScaler()

In [4]:
scalar.transform(data)

array([[0.        , 0.90625   , 0.76086957, 0.        , 0.        ],
       [0.33333333, 1.        , 1.        , 0.75      , 1.        ],
       [1.        , 0.        , 0.        , 1.        , 0.86111111]])

In [5]:
scalar.fit_transform(data)

array([[0.        , 0.90625   , 0.76086957, 0.        , 0.        ],
       [0.33333333, 1.        , 1.        , 0.75      , 1.        ],
       [1.        , 0.        , 0.        , 1.        , 0.86111111]])

# Create a dataframe 

In [6]:
import pandas as pd

In [7]:
my_data=np.random.randint(0,100,(100,6))

In [8]:
df=pd.DataFrame(data=my_data, columns =['f1', 'f2', 'f3', 'f4', 'f5', 'f6'])

In [9]:
df

f1  f2  f3  f4  f5  f6
0   37  40  49  62   5  32
1   65  41  23  58  53  26
2   92   9  55   4  35  52
3   49  75  98  26  87  59
4   13  36  66  71  54  90
..  ..  ..  ..  ..  ..  ..
95  69  62  47  52  48  79
96  79  36  61  52   3  14
97  37   6  93  46  30  94
98  94  20  51  83  74  75
99  46  43  21  61  35  39

[100 rows x 6 columns]

# Create a data frame and conver it Train and Test data sets 

In [10]:
data=np.random.randint(4000,39100,(1000,4))

In [11]:
df=pd.DataFrame(data=data, columns=['f1', 'f2', 'f3', 'lable'])
df.head()

f1     f2     f3  lable
0   5508  13549  12084   6705
1  10065  34184  11869  13194
2  24420  12309  30883  22402
3  23418   7079  21303  29261
4   5204  14887  20863  19372

In [12]:
from sklearn.model_selection import train_test_split

In [14]:
x=df[['f1', 'f2' ,'f3']]

In [15]:
y=df['lable']

In [16]:
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.3)

In [17]:
x_train.head()

f1     f2     f3
309  38308  32619  23968
396   4506  12518  27180
274  17822  20011  30010
734   6794  36269  22048
516  35821  24919  21245

In [18]:
x_train

f1     f2     f3
309  38308  32619  23968
396   4506  12518  27180
274  17822  20011  30010
734   6794  36269  22048
516  35821  24919  21245
..     ...    ...    ...
700  25922  37391  27856
40   22402  27701   5829
248  18449  15038   7662
473  21555  32670  11375
615   8961  35728  38292

[700 rows x 3 columns]

In [19]:
x_test

f1     f2     f3
555   6667  21032  30707
994   6103  10016   5167
669  21767  34135  38775
412  16664  25996  38517
399  30433  33949  24531
..     ...    ...    ...
344  10250  17918  25355
872  12914   6238  29398
467  34601  19134  24546
572  18704  29681   5574
993  15334  33278  20390

[300 rows x 3 columns]

In [20]:
y_train

309     8787
396    35717
274    39061
734    10475
516     4384
       ...  
700    22369
40      4080
248    23341
473    31166
615    25799
Name: lable, Length: 700, dtype: int64

In [21]:
y_test

555     7175
994    21785
669    19920
412    21573
399    12345
       ...  
344    10389
872    38655
467    24194
572    18944
993    28579
Name: lable, Length: 300, dtype: int64