# SciKIt Learn 

In [8]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

Create random multi-dimentional arrray

In [9]:
data=np.random.randint(0,100,(3,5))
data


array([[58, 86, 24, 20, 70],
       [36, 39, 73, 45, 30],
       [38, 85, 60, 46, 19]])

Normalize the data 

In [12]:
scalar=MinMaxScaler()
scalar.fit(data)

MinMaxScaler()

In [13]:
scalar.transform(data)

array([[1.        , 1.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        , 0.96153846, 0.21568627],
       [0.09090909, 0.9787234 , 0.73469388, 1.        , 0.        ]])

In [14]:
scalar.fit_transform(data)

array([[1.        , 1.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        , 0.96153846, 0.21568627],
       [0.09090909, 0.9787234 , 0.73469388, 1.        , 0.        ]])

# Create a dataframe 

In [17]:
import pandas as pd

In [21]:
my_data=np.random.randint(0,100,(100,6))

In [22]:
df=pd.DataFrame(data=my_data, columns =['f1', 'f2', 'f3', 'f4', 'f5', 'f6'])

In [23]:
df

f1  f2  f3  f4  f5  f6
0   37  78  88  74  15  70
1   70   2  86  49  58  65
2   83  47  21  42  15  27
3   82  20   3  12  64   1
4   79  45  62   4  62  27
..  ..  ..  ..  ..  ..  ..
95  73  54  36  29  87   7
96  94  95  84  34  46  42
97  26  85   8  67  36  26
98  36  67  86  84  34  66
99  80   6  40  41  31  16

[100 rows x 6 columns]