In [3]:
import numpy as np 
from sklearn.preprocessing import MinMaxScaler


In [7]:
mat=np.random.randint(0,200,(20,68))
mat

array([[110, 163,  16, ..., 100, 154, 184],
       [ 68, 176,   0, ...,  30, 185,  10],
       [ 82, 169, 180, ...,   9,  52,  51],
       ...,
       [ 58, 195, 126, ..., 111,   6,  39],
       [127,  32, 131, ...,  63, 199, 190],
       [ 59,  73, 111, ...,   6,  47,  17]])

In [9]:
scaler = MinMaxScaler()
scaler.fit(mat)

MinMaxScaler()

In [11]:
scaler.transform(mat)

array([[0.48255814, 0.82142857, 0.08333333, ..., 0.51933702, 0.77040816,
        0.95604396],
       [0.23837209, 0.8877551 , 0.        , ..., 0.13259669, 0.92857143,
        0.        ],
       [0.31976744, 0.85204082, 0.9375    , ..., 0.01657459, 0.25      ,
        0.22527473],
       ...,
       [0.18023256, 0.98469388, 0.65625   , ..., 0.5801105 , 0.01530612,
        0.15934066],
       [0.58139535, 0.15306122, 0.68229167, ..., 0.31491713, 1.        ,
        0.98901099],
       [0.18604651, 0.3622449 , 0.578125  , ..., 0.        , 0.2244898 ,
        0.03846154]])

In [12]:
scaler.fit_transform(mat)

array([[0.48255814, 0.82142857, 0.08333333, ..., 0.51933702, 0.77040816,
        0.95604396],
       [0.23837209, 0.8877551 , 0.        , ..., 0.13259669, 0.92857143,
        0.        ],
       [0.31976744, 0.85204082, 0.9375    , ..., 0.01657459, 0.25      ,
        0.22527473],
       ...,
       [0.18023256, 0.98469388, 0.65625   , ..., 0.5801105 , 0.01530612,
        0.15934066],
       [0.58139535, 0.15306122, 0.68229167, ..., 0.31491713, 1.        ,
        0.98901099],
       [0.18604651, 0.3622449 , 0.578125  , ..., 0.        , 0.2244898 ,
        0.03846154]])

In [13]:
ls

SciKit Learn .ipynb  try1.ipynb


In [16]:
data= np.random.randint(20,459,(10,5))
data

array([[155, 199,  65,  71, 338],
       [ 82, 320, 335, 161, 295],
       [ 83,  32, 125, 431,  90],
       [280, 144, 106, 400, 203],
       [146, 161, 332, 366, 245],
       [135, 424, 358, 339,  65],
       [333, 405,  63, 202, 198],
       [156,  32, 357,  86, 102],
       [139, 196, 350, 128, 386],
       [155,  20, 113, 178,  88]])

In [17]:
import pandas as pd 

In [32]:
df=pd.DataFrame(data=data, columns=['one', 'two', 'three', 'four', 'five'])
df

one  two  three  four  five
0  155  199     65    71   338
1   82  320    335   161   295
2   83   32    125   431    90
3  280  144    106   400   203
4  146  161    332   366   245
5  135  424    358   339    65
6  333  405     63   202   198
7  156   32    357    86   102
8  139  196    350   128   386
9  155   20    113   178    88

In [33]:
df.values

array([[155, 199,  65,  71, 338],
       [ 82, 320, 335, 161, 295],
       [ 83,  32, 125, 431,  90],
       [280, 144, 106, 400, 203],
       [146, 161, 332, 366, 245],
       [135, 424, 358, 339,  65],
       [333, 405,  63, 202, 198],
       [156,  32, 357,  86, 102],
       [139, 196, 350, 128, 386],
       [155,  20, 113, 178,  88]])

In [39]:
df

one  two  three  four  five
0  155  199     65    71   338
1   82  320    335   161   295
2   83   32    125   431    90
3  280  144    106   400   203
4  146  161    332   366   245
5  135  424    358   339    65
6  333  405     63   202   198
7  156   32    357    86   102
8  139  196    350   128   386
9  155   20    113   178    88

In [43]:
from sklearn.model_selection import train_test_split
x=df[['one', 'two', 'three', 'four']]
y=df['five']
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2)

In [44]:
x_train

one  two  three  four
6  333  405     63   202
3  280  144    106   400
0  155  199     65    71
1   82  320    335   161
8  139  196    350   128
7  156   32    357    86
2   83   32    125   431
4  146  161    332   366

In [45]:
y_train

6    198
3    203
0    338
1    295
8    386
7    102
2     90
4    245
Name: five, dtype: int64