# Import Numpy 

In [2]:
import numpy as np

In [3]:
my_list=[1,2,3,4,5,6]

# Transform list into n dimentional array 

In [4]:
arr=np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

# Create an array between 2 numbers 

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10,3)

array([1, 4, 7])

# Create an array with number of zeros 

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Get linear space number array between given 2 numbers with given number of outputs 

In [10]:
np.linspace(0,10,300)

array([ 0.        ,  0.03344482,  0.06688963,  0.10033445,  0.13377926,
        0.16722408,  0.2006689 ,  0.23411371,  0.26755853,  0.30100334,
        0.33444816,  0.36789298,  0.40133779,  0.43478261,  0.46822742,
        0.50167224,  0.53511706,  0.56856187,  0.60200669,  0.63545151,
        0.66889632,  0.70234114,  0.73578595,  0.76923077,  0.80267559,
        0.8361204 ,  0.86956522,  0.90301003,  0.93645485,  0.96989967,
        1.00334448,  1.0367893 ,  1.07023411,  1.10367893,  1.13712375,
        1.17056856,  1.20401338,  1.23745819,  1.27090301,  1.30434783,
        1.33779264,  1.37123746,  1.40468227,  1.43812709,  1.47157191,
        1.50501672,  1.53846154,  1.57190635,  1.60535117,  1.63879599,
        1.6722408 ,  1.70568562,  1.73913043,  1.77257525,  1.80602007,
        1.83946488,  1.8729097 ,  1.90635452,  1.93979933,  1.97324415,
        2.00668896,  2.04013378,  2.0735786 ,  2.10702341,  2.14046823,
        2.17391304,  2.20735786,  2.24080268,  2.27424749,  2.30

# Get random integer 

In [11]:
np.random.randint(2,10)

9

In [12]:
np.random.randint(200,10123, (4,9))

array([[2780, 2762, 9988, 6045, 8341, 3148, 6356, 1848, 2925],
       [3619, 4843, 7966, 8877, 4177, 3299, 4830, 3113, 9634],
       [9197, 5429, 6289, 9571, 1242, 3919, 1929, 4032, 7619],
       [ 893, 8038, 5061,  462, 1208, 1699, 8580,  999, 9556]])

In [13]:
np.linspace(200,10123,10)

array([  200.        ,  1302.55555556,  2405.11111111,  3507.66666667,
        4610.22222222,  5712.77777778,  6815.33333333,  7917.88888889,
        9020.44444444, 10123.        ])

# Create a random value using seed()

It will create random value/s for the paticular given range, to get the same value/s for all the time it needs to use seed()

In [147]:
np.random.seed(10)
np.random.randint(30,100,10)

array([39, 45, 94, 58, 59, 38, 30, 70, 66, 46])

In [148]:
np.random.seed(1)
np.random.randint(30,100,10)

array([67, 42, 39, 35, 94, 46, 31, 36, 55, 80])

As it uses the same seed as 10, it create the same list 

In [149]:
np.random.seed(10)
np.random.randint(30,100,10)

array([39, 45, 94, 58, 59, 38, 30, 70, 66, 46])

works with random values and arrays 

In [157]:
np.random.seed(20)
arr=np.random.randint(20,51,15)
arr


array([23, 46, 35, 48, 46, 29, 40, 31, 42, 27, 22, 20, 42, 28, 41])

In [158]:
arr.max()

48

In [159]:
arr.min()

20

In [160]:
arr.mean()

34.666666666666664

Give out the index of the maximum value of the array


In [162]:
arr.argmax()

3

Give out the inedx of the minimum value of the array 

In [163]:
arr.argmin()

11

Reshape an array 

In [169]:
len(arr)
arr.reshape(3,5)

array([[23, 46, 35, 48, 46],
       [29, 40, 31, 42, 27],
       [22, 20, 42, 28, 41]])

In [172]:
mat= np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [173]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

Get a spesific colums 

In [174]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [178]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

Get a specific row 

In [176]:
mat[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [177]:
mat[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Boolean masking 

In [180]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [182]:
my_filter=mat>50
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])