In [1]:
import numpy as np

In [2]:
list=[1,2,3,4,5,6]
np.array(list)

array([1, 2, 3, 4, 5, 6])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(2,300,5)

array([  2,   7,  12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,
        67,  72,  77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127,
       132, 137, 142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192,
       197, 202, 207, 212, 217, 222, 227, 232, 237, 242, 247, 252, 257,
       262, 267, 272, 277, 282, 287, 292, 297])

In [8]:
np.arange(2,100).reshape(2,49)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99]])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.linspace(1,30,4)

array([ 1.        , 10.66666667, 20.33333333, 30.        ])

In [31]:
# np.random.seed(4)
np.random.randint(2,90, (2,10))

array([[11, 60, 57, 57, 59, 38, 52, 46, 40, 54],
       [ 5,  2, 57, 23, 23, 75, 40, 58, 68, 48]])

In [33]:
list =[3,4,4,44,4657,75,"af"]
np.array(list)


array(['3', '4', '4', '44', '4657', '75', 'af'], dtype='<U21')

In [34]:
np.arange(2,70,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66])

In [36]:
np.arange(3,91).reshape(4,22)

array([[ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
        63, 64, 65, 66, 67, 68],
       [69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90]])

In [37]:
np.zeros(3)

array([0., 0., 0.])

In [39]:
np.zeros([5,9])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.linspace(20,60,4)

array([20.        , 33.33333333, 46.66666667, 60.        ])

In [51]:
np.random.seed(4)
np.random.randint(1,4)

3

In [52]:
np.random.randint(2,10,(3,4))

array([[8, 9, 7, 3],
       [2, 9, 2, 4],
       [3, 4, 6, 9]])

In [55]:
np.arange(2,10).reshape(2,4)

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [56]:
arr=np.arange(0,100)
arr.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
arr=arr.reshape(10,10)

In [62]:
arr[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [63]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
arr[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [68]:
arr[4:7,4:6]

array([[44, 45],
       [54, 55],
       [64, 65]])

In [69]:
my_filter =arr>30

In [70]:
arr[my_filter]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

In [73]:
mat=np.random.randint(0,100,(10,10))
mat

array([[79, 21, 37, 90, 73, 89,  8, 62, 44, 29],
       [53, 20, 54, 66, 82, 65, 19, 55, 95, 20],
       [48, 23, 19, 40, 78, 77, 49, 37,  4, 19],
       [57, 15, 37, 30, 54, 54, 29, 80, 37, 29],
       [ 2, 28, 96, 95, 69,  5, 71,  8, 42, 95],
       [41, 57, 16, 19,  7, 48, 20, 39, 71, 75],
       [17, 67, 48, 39, 76, 59, 30, 65, 31, 69],
       [28, 91, 89, 67, 79, 28, 16,  9, 87, 86],
       [39, 79, 27, 57, 54, 99, 58, 90, 71,  2],
       [ 7, 75, 41, 46, 49,  2, 94, 73, 22, 88]])

In [75]:
my_filter=mat>30
mat[my_filter]

array([79, 37, 90, 73, 89, 62, 44, 53, 54, 66, 82, 65, 55, 95, 48, 40, 78,
       77, 49, 37, 57, 37, 54, 54, 80, 37, 96, 95, 69, 71, 42, 95, 41, 57,
       48, 39, 71, 75, 67, 48, 39, 76, 59, 65, 31, 69, 91, 89, 67, 79, 87,
       86, 39, 79, 57, 54, 99, 58, 90, 71, 75, 41, 46, 49, 94, 73, 88])