In [1]:
import numpy as np

In [3]:
import tensorflow as tf
tf.__version__

AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

In [4]:
list=[1,41,4,6,1]
np.array(list)

array([ 1, 41,  4,  6,  1])

In [5]:
np.arange(2,45)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44])

In [6]:
np.arange(2,100,20)

array([ 2, 22, 42, 62, 82])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.linspace(2,45,40)

array([ 2.        ,  3.1025641 ,  4.20512821,  5.30769231,  6.41025641,
        7.51282051,  8.61538462,  9.71794872, 10.82051282, 11.92307692,
       13.02564103, 14.12820513, 15.23076923, 16.33333333, 17.43589744,
       18.53846154, 19.64102564, 20.74358974, 21.84615385, 22.94871795,
       24.05128205, 25.15384615, 26.25641026, 27.35897436, 28.46153846,
       29.56410256, 30.66666667, 31.76923077, 32.87179487, 33.97435897,
       35.07692308, 36.17948718, 37.28205128, 38.38461538, 39.48717949,
       40.58974359, 41.69230769, 42.79487179, 43.8974359 , 45.        ])

In [10]:
np.random.randint(2,10)

8

In [11]:
np.random.randint(12,40,(4,4))

array([[31, 25, 22, 22],
       [17, 17, 21, 21],
       [31, 15, 27, 35],
       [18, 16, 37, 28]])

In [12]:
arr=np.arange(3,45,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [13]:
arr.reshape(2,7)

array([[ 3,  6,  9, 12, 15, 18, 21],
       [24, 27, 30, 33, 36, 39, 42]])

In [14]:
array=np.arange(0,100).reshape(10,10)
array


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
array[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
array[4,:3]

array([40, 41, 42])

In [21]:
array[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [22]:
array[4:7,4:8]

array([[44, 45, 46, 47],
       [54, 55, 56, 57],
       [64, 65, 66, 67]])

In [25]:
mat=np.random.randint(2,304,(5,3))
mat


array([[137, 194,   3],
       [275, 125, 218],
       [ 61, 201, 239],
       [226,  34,  12],
       [277, 205, 115]])

In [26]:
my_filter=mat>10
mat[my_filter]

array([137, 194, 275, 125, 218,  61, 201, 239, 226,  34,  12, 277, 205,
       115])