In [61]:
import numpy as np

Covert array in to list

In [62]:
list=[1,2,3,4,5,5]
arr=np.array(list)

In [63]:
type(arr)

numpy.ndarray

create an array

In [64]:
arr =np.arange(0,100,4)
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [65]:
arr_z=np.zeros((4,5))
arr_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
arr_z2=np.zeros(3)
arr_z2

array([0., 0., 0.])

In [81]:
linspace = np.linspace(20,50,3)
linspace

array([20., 35., 50.])

In [94]:

ran_arr=np.random.randint(2,850,100)
ran_arr

array([840, 105, 818,  45, 832, 229, 297, 212, 658, 279, 552,  63, 251,
       471, 232, 482,  66,  89, 510, 464, 258, 280, 513, 155, 602, 714,
       617, 222, 109, 615, 762, 187, 120, 247, 627, 684, 778, 401, 498,
       324,  52, 133, 432,  29, 697,  66, 205, 151, 511, 593, 752, 160,
       722, 273, 365, 649, 709, 465, 471, 170, 651, 238, 580, 467, 162,
       181,  21, 734, 297, 714, 848,   7, 503, 390, 192, 164, 181, 156,
       789, 104, 760, 631,  57, 623,  24, 646, 756, 820, 526, 470, 219,
       326, 270, 586, 492, 384, 171, 540, 169,  49])

In [95]:
def insertionSort(ran_arr):
    for i in range(len(ran_arr)-1):
        if ran_arr[i]>ran_arr[i+1]:
            for j in range(i+1, 0, -1):
                if ran_arr[j]<ran_arr[j-1]:
                    temp=ran_arr[j]
                    ran_arr[j]=ran_arr[j-1]
                    ran_arr[j-1]=temp
    return ran_arr
print(insertionSort(ran_arr))

[  7  21  24  29  45  49  52  57  63  66  66  89 104 105 109 120 133 151
 155 156 160 162 164 169 170 171 181 181 187 192 205 212 219 222 229 232
 238 247 251 258 270 273 279 280 297 297 324 326 365 384 390 401 432 464
 465 467 470 471 471 482 492 498 503 510 511 513 526 540 552 580 586 593
 602 615 617 623 627 631 646 649 651 658 684 697 709 714 714 722 734 752
 756 760 762 778 789 818 820 832 840 848]


In [96]:
print(insertionSort(ran_arr))

[  7  21  24  29  45  49  52  57  63  66  66  89 104 105 109 120 133 151
 155 156 160 162 164 169 170 171 181 181 187 192 205 212 219 222 229 232
 238 247 251 258 270 273 279 280 297 297 324 326 365 384 390 401 432 464
 465 467 470 471 471 482 492 498 503 510 511 513 526 540 552 580 586 593
 602 615 617 623 627 631 646 649 651 658 684 697 709 714 714 722 734 752
 756 760 762 778 789 818 820 832 840 848]


In [107]:
# create array 0-100
arr=np.arange(0,100)
arr=arr.reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [106]:
arr[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [108]:
arr[9,:]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [110]:
arr[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [114]:
arr[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [126]:
a=np.random.randint(20,50,(10,10))
a

array([[40, 39, 34, 35, 40, 46, 39, 21, 24, 30],
       [23, 23, 28, 27, 38, 32, 48, 43, 26, 35],
       [36, 38, 22, 21, 32, 32, 47, 24, 39, 47],
       [45, 20, 44, 22, 23, 23, 47, 45, 43, 32],
       [31, 49, 31, 21, 43, 43, 46, 43, 21, 31],
       [26, 37, 38, 26, 45, 48, 35, 29, 38, 32],
       [31, 49, 30, 24, 39, 28, 23, 44, 21, 25],
       [36, 37, 20, 49, 45, 49, 35, 31, 48, 30],
       [33, 48, 37, 42, 43, 48, 27, 21, 37, 24],
       [31, 47, 37, 36, 41, 30, 33, 47, 28, 34]])

In [127]:
a[0:3,0:3]

array([[40, 39, 34],
       [23, 23, 28],
       [36, 38, 22]])

In [128]:
a[3:7,4:7]

array([[23, 23, 47],
       [43, 43, 46],
       [45, 48, 35],
       [39, 28, 23]])

In [138]:
# bolean masking 
mat =np.random.randint(2,450,(12,39))
mat

array([[ 86, 260, 354, 106, 253,  69, 290, 430, 418, 393, 105, 322, 263,
          4, 434, 149, 317, 411, 239, 412, 350, 387, 241,   3,  61, 321,
        180, 179, 322, 260, 266, 402, 447, 260, 162,  63,  76,   9, 441],
       [277, 145,  44, 183,  50, 200, 380, 229, 236,  83, 312, 350, 398,
        267, 343,  53, 192, 195, 189, 416,  92, 250, 152,  52, 195, 369,
        170, 295, 348, 328, 192, 225, 236,  89, 303, 215,  53, 402, 113],
       [373,  57, 121, 348, 287, 234,   6, 239, 280, 328, 341, 189,  92,
        343, 135,  40, 359, 297, 135, 273, 441, 341, 106, 109,  70, 246,
          5, 386, 169,  96,  79, 147,  51, 241, 118, 206, 169, 133,  60],
       [106, 410,  10,  85, 386, 408, 389, 442, 182, 311, 212, 191, 446,
         41, 313,  95, 264, 117,  45, 368, 346, 285,  15,  96, 399, 344,
        188, 172, 100, 234, 171, 107, 221,  11, 110, 188, 307,  10, 352],
       [ 18, 366, 232, 168, 364, 329, 308,  19, 257,  44,  65, 126,  91,
        138, 409, 333, 167,  46, 448, 200, 220,

In [142]:
my_filter = mat>430
mat=mat[my_filter]
mat

array([434, 447, 441, 441, 442, 446, 448, 444, 443, 448, 441, 448, 431,
       431, 443, 448, 436, 437, 437, 449, 434, 438, 439])